language: android

sudo: false

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/

notifications:
  email: false

env:
  global:
    - INSTALL_PKGS='build-tools-21.1.2'
    - UPDATE_PKGS='platform-tools,tools,extra-android-m2repository,extra-google-m2repository'
    - GRADLE_USER_HOME="${TRAVIS_BUILD_DIR}/gradle"
    - ADB_INSTALL_TIMEOUT=8 # minutes (2 minutes by default)
    - AVD_DEBUG='init,avd_config,nand_limits,keys,adb,adbserver,adbclient'
    - ANDROID_LOG_TAGS='NetworkStats:S dalvikvm:S Zygote:S Resources:S *:D'
    - ANDROID_SERIAL='emulator-5554'
    - ANDROID_HOME='/usr/local/android-sdk'
    - PATH="${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${PATH}"

matrix:
  include:
    - env: AVD_TARGET=android-15
    - env: AVD_TARGET=android-17
    - env: AVD_TARGET=android-19
    - env: AVD_TARGET=android-21
    - env: AVD_TARGET='Google Inc.:Google APIs:21' AVD_TAG=google_apis
           TARGET_PKGS=addon-google_apis-google-21,sys-img-armeabi-v7a-addon-google_apis-google-21
  allow_failures:
    - env: AVD_TARGET='Google Inc.:Google APIs:21' AVD_TAG=google_apis
           TARGET_PKGS=addon-google_apis-google-21,sys-img-armeabi-v7a-addon-google_apis-google-21
  fast_finish: true

before_install:
  - chmod +x gradlew
  - ./execute inexistent install-and-update-sdk
  - ./execute create-and-start-device wait-for-device-online

install:
  - ./gradlew --version # show version and download Gradle Wrapper when is not present in cache
  - ./gradlew clean # clean project and download Android dependencies when are not present in cache
  - ./gradlew assemble

before_script:
  - ./execute wait-for-device-ready inexistent

script:
  - ./gradlew connectedCheck

after_script:
  - cat ${TRAVIS_BUILD_DIR}/espresso/*/app/build/outputs/androidTest-results/connected/* # show logs